"""Media muxing checks against the real resident executable (Windows).

Generates small real-media fixtures with ffmpeg (a test-only tool; the
product never runs it), serves them as DASH and HLS from a local server,
seeds one media job per muxer into an isolated portable store, and lets the
real engine download and mux each one. For every output the run records the
state, size, SHA-256, the streams ffprobe sees and whether ffmpeg decodes it
without errors. A large synthetic dual-track download measures the
resident's peak memory, which must stay far below the size of the media.

  python e2e/media.py [--no-build] [--exe PATH] [--big-mib 1024]
                      [--compare e2e/results/media-<stamp>.json] [--label NAME]

--exe runs another build (for example the previous engine, to show a check
is not vacuous); --compare adds a check that every output is byte-identical
to the same scenario in an earlier run. Writes e2e/results/media-<stamp>.json
and exits non-zero if any check fails.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import importlib.util
import json
import shutil
import socket
import sqlite3
import struct
import subprocess
import sys
import tempfile
import threading
import time
from http.server import ThreadingHTTPServer
from pathlib import Path

import psutil

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "e2e" / "results"
CACHE = ROOT / "e2e" / ".media-cache"
MIB = 1024 * 1024
BIG_SEGMENT = 64 * MIB

spec = importlib.util.spec_from_file_location("fixture", ROOT / "fixtures" / "server.py")
fixture = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fixture)

LAVFI = ["-f", "lavfi", "-i", "testsrc=size=320x240:rate=25", "-f", "lavfi", "-i", "sine=frequency=440:sample_rate=48000", "-t", "6", "-map", "0:v", "-map", "1:a"]
VP9 = ["-c:v", "libvpx-vp9", "-b:v", "300k", "-deadline", "realtime", "-cpu-used", "8", "-g", "50"]
FIXTURES = {
    # name: (ffmpeg arguments after the inputs, manifest file)
    "webm": (VP9 + ["-c:a", "libopus", "-b:a", "64k", "-f", "dash", "-seg_duration", "2", "-dash_segment_type", "webm", "-use_template", "1", "-use_timeline", "0", "manifest.mpd"], "manifest.mpd"),
    "mixed": (VP9 + ["-c:a", "aac", "-b:a", "96k", "-f", "dash", "-seg_duration", "2", "-dash_segment_type", "auto", "-use_template", "1", "-use_timeline", "0", "manifest.mpd"], "manifest.mpd"),
    "hls": (["-c:v", "libx264", "-preset", "ultrafast", "-g", "50", "-c:a", "aac", "-b:a", "96k", "-f", "hls", "-hls_time", "2", "-hls_playlist_type", "vod", "-hls_segment_type", "mpegts", "-var_stream_map", "v:0,agroup:aud a:0,agroup:aud,default:yes", "-master_pl_name", "master.m3u8", "-hls_segment_filename", "s%v-%d.ts", "p%v.m3u8"], "master.m3u8"),
}


def ensure_fixtures() -> None:
    # Generated once and kept, so every run (and every build compared) is
    # fed the same bytes.
    for name, (args, _) in FIXTURES.items():
        folder = CACHE / name
        if (folder / "done").is_file():
            continue
        shutil.rmtree(folder, ignore_errors=True)
        folder.mkdir(parents=True)
        subprocess.run(["ffmpeg", "-v", "error", *LAVFI, *args], cwd=folder, check=True)
        (folder / "done").write_text("generated by e2e/media.py\n", encoding="utf-8")


def mp4_box(kind: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", 8 + len(payload)) + kind + payload


def full_box(kind: bytes, version: int, flags: int, payload: bytes) -> bytes:
    return mp4_box(kind, bytes([version]) + flags.to_bytes(3, "big") + payload)


def init_field(init: bytes, kind: bytes) -> int:
    # tkhd track_ID / mdhd timescale: the u32 after the version-dependent times.
    at = init.index(kind) + 4
    return struct.unpack(">I", init[at + (12 if init[at] == 0 else 20):][:4])[0]


class BigMedia:
    """A synthetic dual-track DASH presentation of any size: the real
    fixture's video initialization with large one-sample fragments, and the
    real audio track. The bytes are never decoded; the engine only muxes."""

    def __init__(self, mib: int) -> None:
        self.init = fixture.media_file("v-init.mp4")
        self.track_id = init_field(self.init, b"tkhd")
        self.timescale = init_field(self.init, b"mdhd")
        self.count = max(1, mib * MIB // BIG_SEGMENT)
        self.payload = bytes(range(256)) * (BIG_SEGMENT // 256)

    def manifest(self) -> bytes:
        video = "".join(f'<SegmentURL media="v-{i}.m4s"/>' for i in range(self.count))
        return (
            f'<MPD type="static" mediaPresentationDuration="PT{self.count * 4}S"><Period>'
            '<AdaptationSet contentType="video"><Representation id="v">'
            f'<BaseURL>/big/</BaseURL><SegmentList><Initialization sourceURL="v-init.mp4"/>{video}</SegmentList>'
            "</Representation></AdaptationSet>"
            '<AdaptationSet contentType="audio"><Representation id="a">'
            '<BaseURL>/dash/</BaseURL><SegmentList><Initialization sourceURL="a-init.mp4"/><SegmentURL media="a-0.m4s"/></SegmentList>'
            "</Representation></AdaptationSet></Period></MPD>"
        ).encode()

    def segment_header(self, index: int) -> bytes:
        mfhd = full_box(b"mfhd", 0, 0, struct.pack(">I", index + 1))
        tfhd = full_box(b"tfhd", 0, 0x020000, struct.pack(">I", self.track_id))
        tfdt = full_box(b"tfdt", 1, 0, struct.pack(">Q", index * 4 * self.timescale))

        def moof(offset: int) -> bytes:
            trun = full_box(b"trun", 0, 0x000201, struct.pack(">IiI", 1, offset, len(self.payload)))
            return mp4_box(b"moof", mfhd + mp4_box(b"traf", tfhd + tfdt + trun))

        return moof(len(moof(0)) + 8) + struct.pack(">I", 8 + len(self.payload)) + b"mdat"


BIG: BigMedia | None = None


class Handler(fixture.Handler):
    def _raw(self, data: bytes, kind: str, tail: bytes = b"") -> None:
        self.send_response(200)
        self.send_header("Content-Type", kind)
        self.send_header("Content-Length", str(len(data) + len(tail)))
        self.end_headers()
        try:
            self.wfile.write(data)
            if tail:
                self.wfile.write(tail)
        except (BrokenPipeError, ConnectionResetError, ConnectionAbortedError):
            pass

    def do_GET(self):  # noqa: N802
        path = self.path.split("?")[0]
        if path.startswith("/mc/"):
            file = (CACHE / path[4:]).resolve()
            if CACHE.resolve() in file.parents and file.is_file():
                kind = "application/dash+xml" if file.suffix == ".mpd" else "application/vnd.apple.mpegurl" if file.suffix == ".m3u8" else "video/mp2t" if file.suffix == ".ts" else "video/webm" if file.suffix == ".webm" else "video/mp4"
                return self._raw(file.read_bytes(), kind)
            return self._send_bytes(b"missing fixture", 404)
        if path == "/big/manifest.mpd" and BIG:
            return self._raw(BIG.manifest(), "application/dash+xml")
        if path == "/big/v-init.mp4" and BIG:
            return self._raw(BIG.init, "video/mp4")
        if path.startswith("/big/v-") and BIG:
            index = int(path[len("/big/v-"):-len(".m4s")])
            return self._raw(BIG.segment_header(index), "video/mp4", BIG.payload)
        return super().do_GET()


class Run:
    def __init__(self) -> None:
        self.results: list[dict] = []

    def check(self, scenario: str, guards: str, ok: bool, evidence: dict) -> None:
        self.results.append({"scenario": scenario, "guards": guards, "pass": bool(ok), "evidence": evidence})
        print(f"{'PASS' if ok else 'FAIL'}  {scenario}  - {guards}")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while chunk := handle.read(MIB):
            digest.update(chunk)
    return digest.hexdigest()


def probe(path: Path) -> dict:
    shown = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "stream=codec_type,codec_name:format=format_name,duration", "-of", "json", str(path)], capture_output=True, text=True)
    decoded = subprocess.run(["ffmpeg", "-v", "error", "-i", str(path), "-f", "null", "-"], capture_output=True, text=True)
    info = json.loads(shown.stdout or "{}")
    return {
        "streams": sorted(f"{s.get('codec_type')}:{s.get('codec_name')}" for s in info.get("streams", [])),
        "format": info.get("format", {}).get("format_name"),
        "duration": info.get("format", {}).get("duration"),
        "decodeErrors": decoded.stderr.strip().splitlines()[:5],
        "decodeExit": decoded.returncode,
    }


def main() -> int:
    global BIG
    parser = argparse.ArgumentParser()
    parser.add_argument("--no-build", action="store_true")
    parser.add_argument("--exe", help="resident build to run (default: target/debug)")
    parser.add_argument("--big-mib", type=int, default=1024, help="size of the synthetic memory scenario; 0 skips it")
    parser.add_argument("--compare", help="earlier media result file whose outputs must be byte-identical")
    parser.add_argument("--label", default="", help="free-form note stored in the result (e.g. which build)")
    parser.add_argument("--keep", action="store_true", help="keep the isolated runtime folder (track files, log)")
    args = parser.parse_args()

    with socket.socket() as probe_socket:
        if probe_socket.connect_ex(("127.0.0.1", 38217)) == 0:
            print("Port 38217 is in use: quit the running Download Manager first.")
            return 2
    for tool in ("ffmpeg", "ffprobe"):
        if not shutil.which(tool):
            print(f"{tool} is required to generate and check the media fixtures.")
            return 2
    if not args.no_build and not args.exe:
        subprocess.run(["cargo", "build", "--manifest-path", str(ROOT / "src-tauri" / "Cargo.toml")], check=True)
    ensure_fixtures()
    BIG = BigMedia(args.big_mib) if args.big_mib > 0 else None

    runtime = Path(tempfile.mkdtemp(prefix="dm-media-e2e-"))
    (runtime / "data").mkdir()
    out = runtime / "out"
    exe = runtime / "download-manager.exe"
    shutil.copy2(Path(args.exe) if args.exe else ROOT / "src-tauri" / "target" / "debug" / "download-manager.exe", exe)

    server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
    threading.Thread(target=server.serve_forever, daemon=True).start()
    base = f"http://127.0.0.1:{server.server_port}"

    jobs_to_run = {
        # name: (manifest path, requested file name, muxer it reaches)
        "fmp4": ("/dash/manifest.mpd", "fmp4.mp4", "fragmented MP4 video + audio"),
        "webm": ("/mc/webm/manifest.mpd", "webm.webm", "WebM VP9 + WebM Opus into Matroska"),
        "mixed": ("/mc/mixed/manifest.mpd", "mixed.webm", "WebM VP9 + fragmented-MP4 AAC into Matroska"),
        "ts": ("/mc/hls/master.m3u8", "ts.ts", "MPEG-TS video + separate MPEG-TS audio"),
    }
    if BIG:
        jobs_to_run["large"] = ("/big/manifest.mpd", "large.mp4", f"{BIG.count * BIG_SEGMENT // MIB} MiB fragmented MP4 video + audio")

    db = runtime / "data" / "download-manager.db"
    con = sqlite3.connect(db)
    con.executescript("CREATE TABLE jobs (id TEXT PRIMARY KEY, created_at TEXT NOT NULL, payload TEXT NOT NULL); CREATE TABLE settings (id INTEGER PRIMARY KEY, payload TEXT NOT NULL); CREATE TABLE notifications (id TEXT PRIMARY KEY, payload TEXT);")
    con.execute("INSERT INTO settings VALUES (1, ?)", (json.dumps({"startAtSignIn": False, "showManagerAtSignIn": False, "retryAutomatically": True, "maxRetries": 2, "completionNotifications": False, "failureNotifications": False, "defaultFolder": str(out)}),))
    for name, (path, file_name, _) in jobs_to_run.items():
        job = dict(id=name, name=file_name, source=base + path, domain="127.0.0.1", state="connecting", progress=0, downloaded=0, total=None, speed=0, eta=None, connections=0, maxConnections=4, mode="single-stream", media=True, playerKind="video", destination=str(out / file_name), tempPath=str(runtime / "data" / "tmp" / f"{name}.part"), resumable=False, mime=None, error=None, created="2026-10-01T09:00:00Z", started=None, completed=None, provisional=False, segments=None, referrer=base + "/page", events=[])
        con.execute("INSERT INTO jobs VALUES (?, ?, ?)", (name, job["created"], json.dumps(job)))
    con.commit()
    con.close()

    log = open(runtime / "app.log", "w", encoding="utf-8")
    started = time.time()
    app = subprocess.Popen([str(exe), "--startup"], cwd=runtime, stdout=log, stderr=log, creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    process = psutil.Process(app.pid)
    run = Run()
    peak_private = 0
    finished_at: dict[str, float] = {}

    def jobs() -> dict[str, dict]:
        with sqlite3.connect(db) as connection:
            return {j["id"]: j for (payload,) in connection.execute("SELECT payload FROM jobs") for j in [json.loads(payload)]}

    try:
        state: dict[str, dict] = {}
        deadline = time.time() + 900
        while time.time() < deadline:
            time.sleep(0.25)
            try:
                peak_private = max(peak_private, process.memory_info().private)
                state = jobs()
            except (sqlite3.Error, psutil.Error):
                continue
            for name in jobs_to_run:
                if state.get(name, {}).get("state") in ("completed", "failed"):
                    finished_at.setdefault(name, round(time.time() - started, 1))
            if len(finished_at) == len(jobs_to_run):
                break
        memory = process.memory_info()
        memory_evidence = {"peakCommitMiB": round(memory.peak_pagefile / MIB, 1), "peakWorkingSetMiB": round(memory.peak_wset / MIB, 1), "sampledPeakPrivateMiB": round(peak_private / MIB, 1)}
    finally:
        app.terminate()
        try:
            app.wait(timeout=15)
        except subprocess.TimeoutExpired:
            app.kill()
        log.close()
        server.shutdown()

    compare = {}
    if args.compare:
        earlier = json.loads(Path(args.compare).read_text(encoding="utf-8"))
        compare = {r["scenario"]: r["evidence"].get("sha256") for r in earlier["results"] if r["evidence"].get("sha256")}

    outputs = {}
    for name, (_, _, reaches) in jobs_to_run.items():
        j = state.get(name, {})
        dest = Path(j.get("destination") or out / "missing")
        evidence = {"state": j.get("state"), "error": j.get("error"), "file": dest.name, "seconds": finished_at.get(name)}
        if dest.is_file():
            evidence.update(bytes=dest.stat().st_size, sha256=sha256(dest))
            if name != "large":
                evidence.update(probe(dest))
        outputs[name] = evidence
        scenario = f"mux/{name}"
        if name == "large":
            ok = evidence["state"] == "completed" and evidence.get("bytes", 0) >= BIG.count * BIG_SEGMENT
            run.check(scenario, f"a {reaches} download completes", ok, evidence)
            ceiling = 512
            run.check("mux/large-memory", f"muxing {BIG.count * BIG_SEGMENT // MIB} MiB of media keeps the resident's peak commit under {ceiling} MiB (it grows with the header count, not the media size)", ok and memory_evidence["peakCommitMiB"] < ceiling, {**memory_evidence, "mediaMiB": BIG.count * BIG_SEGMENT // MIB})
        else:
            expected = {"video", "audio"}
            kinds = {stream.split(":")[0] for stream in evidence.get("streams", [])}
            ok = evidence["state"] == "completed" and kinds == expected and evidence.get("decodeExit") == 0 and not evidence.get("decodeErrors")
            run.check(scenario, f"{reaches}: completes, carries one video and one audio stream, and decodes without errors", ok, evidence)
        if compare:
            same = compare.get(scenario) == evidence.get("sha256") and evidence.get("sha256") is not None
            run.check(f"equivalence/{name}", "the output is byte-identical to the compared run", same, {"now": evidence.get("sha256"), "compared": compare.get(scenario)})

    RESULTS.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
    target = RESULTS / f"media-{stamp}.json"
    passed = sum(r["pass"] for r in run.results)
    target.write_text(json.dumps({"run": stamp, "label": args.label, "exe": str(args.exe or "target/debug"), "compare": args.compare, "passed": passed, "total": len(run.results), "memory": memory_evidence, "results": run.results, "appLog": (runtime / "app.log").read_text(encoding="utf-8", errors="replace")[-4000:]}, indent=2), encoding="utf-8")
    print(f"\n{passed}/{len(run.results)} passed; results in {target}")
    if args.keep:
        print("Runtime kept at", runtime)
    else:
        shutil.rmtree(runtime, ignore_errors=True)
    return 0 if passed == len(run.results) else 1


if __name__ == "__main__":
    sys.exit(main())
